name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: ls -la

      - name: Run sample command
        run: echo "Testing workflow working!"